@extends('layouts.front')
@section('head')
  @include('parts.head')
@endsection
@section('single-blog')
  @include('parts.single-blog')
@endsection
@section('footer')
  @include('parts.footer')
@endsection
